server:
  port: 8092

spring:
  application:
    name: fraud
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: rootpassword
      database: fraud
      port: 27017
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
