server:
  port: 8092

spring:
  application:
    name: fraud
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: rootpassword
      database: fraud
      port: 27018
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: mqadmin
    password: mqadmin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
